stages:
  - gosec
  - test

variables:

  #GLOBAL
  IMAGE_NAME: eth2-key-manager

  #STAGE
  ACCOUNT_ID_INFRA_STAGE: 121827225315
  AWS_REGION_INFRA_STAGE: "us-west-2"
  DOCKER_REPO_INFRA_STAGE: $ACCOUNT_ID_INFRA_STAGE.dkr.ecr.$AWS_REGION_INFRA_STAGE.amazonaws.com/$IMAGE_NAME
  APP_REPLICAS_INFRA_STAGE: "1"
  ECRLOGIN_INFRA_STAGE: "aws ecr get-login --registry-ids $ACCOUNT_ID_INFRA_STAGE --region $AWS_REGION_INFRA_STAGE --no-include-email"


Security check:
  stage: gosec
  image: golang:1.14-stretch
  tags:
    - blox-infra-stage
  script:
    - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.5.0
    - ./bin/gosec -exclude G104 ./...

Test stage Docker image:
  stage: test
  image: golang:1.14-stretch
  tags:
    - blox-infra-stage 
  script:
    - go test -v -cover -race -p 1 ./...
